language: elixir
sudo: false
cache:
  directories:
    - _build
    - deps
branches:
  only:
    - master
elixir: '1.10'
otp_release: '23.0'
stages:
  - test
  - name: inch
    if: type = push
jobs:
  include:
    - stage: test

    - opt_release: '22.2'
      elixir: '1.9'

    - otp_release: '21.2'
      elixir: '1.8'

    - stage: inch
      script:
        - mix deps.get --only docs
        - MIX_ENV=docs mix inch.report
notifications:
  recipients:
    - steve@stevedomin.com
